### ISSUE TITLE
Documentation to-dos

### ISSUE THREAD

**Issue by st--** [st--/annotate-equations#28]
- [ ] page-flip behaviour (see #12)
- [ ] clarify direction of the annotation arrows for when you want to change the styling (see #19)
- [ ] add mention that one should always finish with `%` after the `\annotate`(`two`) command to avoid inadvertent spacing issues (see #24)
